import tracery
from tracery.modifiers import base_english

rules = {
    'origin': ['#story#'],
    'story' : ['#mp#', '#pre#'],
    'mp'  : ['#M+_names.capitalize# of the #suffix#', '#prefix.capitalize# #M+_names#'],
    'pre'  : [
        '#pre_names.capitalize# of the #pre_suffix#',
        '#pre_prefix.capitalize# #pre_names#',
        '#pre_names.capitalize# #pre_prop_suffix#'],
    'M+_names': ['data library', 'archives', 'laboratory', 'orbital Station', 'ocean prison', 'asteroid mining colony'],
    'suffix' : ['valley', 'forest', 'jungle'],
    'prefix' : ['#moods#', '#passages#','shadow state', 'secluded', 'nano', 'ruined', 'evil', 'forgotten'],

    'pre_names' : ['#passages#', 'keep', 'forest', 'valley', 'desert', 'tomb'],
    'pre_prop_suffix' : ['of #greek_gods#', 'of #lc_gods#', 'of #gemstones.s#'], # THING _____
    'pre_suffix' : ['#elemental.capitalize# Wyrm', 'decaying', 'wastes'], # OF THE ____
    'pre_prefix' : ['#lc_gods#`s', '#moods#', 'unholy', 'forgotten'],  # _____ THING

    'elemental' : [
        "fire",
        "ice",
        "lightning",
        "poison",
        "cursed",
        "dark",
        "void",
        "iron",
        "divine",
    ],

    'lc_gods' : [
        "Azathoth",
        "Bastet",
        "Cthugha",
        "Cthulhu",
        "Cthylla",
        "Cxaxukluth",
        "Cyaegha",
        "Dagon",
        "Ghatanothoa",
        "Ghisguth",
        "Gla'aki",
        "Great Old One",
        "Hastur",
        "Hypnos",
        "Hziulquoigmnzhah",
        "Ithaqua",
        "Knygathin Zhaum",
        "Nodens",
        "Nyarlathotep",
        "Outer God",
        "Sfatlicllp",
        "Shathak",
        "Shub-Niggurath",
        "Tsathoggua",
        "Ubbo-Sathla",
        "Vulthoom",
        "Y'golonac",
        "Ycnagnnisssz",
        "Yig",
        "Yog-Sothoth",
        "Ythogtha",
        "Zoth-Ommog",
        "Zstylzhemghi",
        "Zvilpogghua"
    ],

    "greek_gods": [
        "Aphrodite",
        "Apollo",
        "Ares",
        "Artemis",
        "Athena",
        "Demeter",
        "Dionysus",
        "Hades",
        "Hephaestus",
        "Hera",
        "Hermes",
        "Hestia",
        "Poseidon",
        "Zeus",
        "Aether",
        "Ananke",
        "Chaos",
        "Chronos",
        "Erebus",
        "Eros",
        "Hypnos",
        "Uranus",
        "Gaia",
        "Phanes",
        "Pontus",
        "Tartarus",
        "Thalassa",
        "Thanatos",
        "Hemera",
        "Nyx",
        "Nemesis"
    ],

    "gemstones":
    [
      "actinolite",
      "adamite",
      "aegerine",
      "afghanite",
      "agardite",
      "agate",
      "ajoite",
      "alabaster",
      "albite",
      "alexandrite",
      "almandine",
      "alunite",
      "amazonite",
      "amber",
      "amethyst",
      "ametrine",
      "ammolite",
      "analcime",
      "anatase",
      "andalusite",
      "andesine",
      "andradite",
      "anglesite",
      "anhydrite",
      "ankerite",
      "annabergite",
      "anthophyllite",
      "antigorite",
      "antlerite",
      "anyolite",
      "apache tears",
      "apophyllite",
      "aquamarine",
      "aragonite",
      "astrophyllite",
      "atacamite",
      "augite",
      "aurichalcite",
      "austinite",
      "aventurine",
      "axinite",
      "azurite",
      "barite",
      "baryte",
      "bauxite",
      "bayldonite",
      "benitoite",
      "beryl",
      "beudantite",
      "biotite",
      "bixbite",
      "blue amber",
      "boleite",
      "bone",
      "boracite",
      "bornite",
      "botallackite",
      "botryogen",
      "bowenite",
      "brazilianite",
      "brochantite",
      "bronzite",
      "brookite",
      "brucite",
      "bubblegram",
      "bytownite",
      "cacoxenite",
      "calcite",
      "caledonite",
      "californite",
      "carletonite",
      "carminite",
      "carnallite",
      "carnelian",
      "cassiterite",
      "castorite",
      "cavansite",
      "celestine",
      "celestite",
      "cerussite",
      "ceylonite",
      "chalcedony",
      "chalcopyrite",
      "chambersite",
      "charoite",
      "chlorastrolite",
      "chloromelanite",
      "chondrodite",
      "chrysoberyl",
      "chrysocolla",
      "chrysotile",
      "cinnabar",
      "citrine",
      "clinochlore",
      "clinohumite",
      "clinozoisite",
      "clintonite",
      "conichalcite",
      "copal",
      "coral",
      "cordierite",
      "corundum",
      "creedite",
      "crocidolite",
      "cummingtonite",
      "cuprite",
      "cymophane",
      "danburite",
      "datolite",
      "diaboleite",
      "diamond",
      "diaspore",
      "diopside",
      "dioptase",
      "dolomite",
      "dravite",
      "druzy",
      "dumortierite",
      "eilat stone",
      "ekanite",
      "elaeolite",
      "elbaite",
      "emerald",
      "enstatite",
      "epidosite",
      "epidote",
      "erythrite",
      "esperite",
      "fayalite",
      "feldspar",
      "ferroaxinite",
      "flint",
      "fluorapatite",
      "fluorapophyllite",
      "fluorite",
      "forsterite",
      "garnet",
      "garnierite",
      "gibbsite",
      "glaucophane",
      "goethite",
      "goshenite",
      "grandidierite",
      "grossular",
      "gypsum",
      "halite",
      "hambergite",
      "hanksite",
      "hardystonite",
      "hauyne",
      "helenite",
      "heliodor",
      "hematite",
      "hemimorphite",
      "hessonite",
      "hibonite",
      "hiddenite",
      "humite",
      "iddingsite",
      "idocrase",
      "iolite",
      "ivory",
      "jacinth",
      "jade",
      "jadeite",
      "jarosite",
      "jasper",
      "jeremejevite",
      "jet",
      "kainite",
      "kidney ore",
      "kimberlite",
      "kornerupine",
      "kunzite",
      "kutnohorite",
      "kyanite",
      "labradorite",
      "lammerite",
      "langbeinite",
      "langite",
      "lapis lazuli",
      "larimar",
      "lawsonite",
      "lazurite",
      "leadhillite",
      "lechatelierite",
      "legrandite",
      "lepidolite",
      "leucophanite",
      "linarite",
      "londonite",
      "magnesioaxinite",
      "magnesite",
      "malachite",
      "manganaxinite",
      "manganoan calcite",
      "maw sit sit",
      "melanterite",
      "mendipite",
      "metal-coated crystals",
      "milky quartz",
      "mimetite",
      "moissanite",
      "mookaite",
      "moonstone",
      "morganite",
      "muscovite",
      "musgravite",
      "nacre",
      "natrophilite",
      "nepheline",
      "nephrite",
      "nimite",
      "normandite",
      "obsidian",
      "olenite",
      "olivenite",
      "olivine",
      "olivinite",
      "onyx",
      "opal",
      "orthoclase",
      "pallasite",
      "pantellerite",
      "papagoite",
      "pargasite",
      "pearl",
      "pectolite",
      "peridot",
      "peridotite",
      "petalite",
      "petoskey stone",
      "pezzottaite",
      "pharmacosiderite",
      "phlogopite",
      "phosgenite",
      "pietersite",
      "pimelite",
      "plancheite",
      "plumbogummite",
      "pollucite",
      "polyhalite",
      "posnjakite",
      "poudretteite",
      "prasiolite",
      "prehnite",
      "proustite",
      "pumpellyite",
      "purpurite",
      "pyrite",
      "pyromorphite",
      "pyrope",
      "pyrrhotite",
      "quartz",
      "raspite",
      "rhodizite",
      "rhodochrosite",
      "riebeckite",
      "rosasite",
      "rose quartz",
      "rossmanite",
      "rubellite",
      "ruby",
      "rutile",
      "sapphire",
      "sardonyx",
      "scapolite",
      "scheelite",
      "schorlomite",
      "scolecite",
      "scorodite",
      "selenite",
      "seraphinite",
      "serendibite",
      "serpentite",
      "shattuckite",
      "shigaite",
      "siderite",
      "smithsonite",
      "smoky quartz",
      "soapstone",
      "sodalite",
      "spessartine",
      "spessartite",
      "sphene",
      "spherocobaltite",
      "spinel",
      "spodumene",
      "steatite",
      "stichtite",
      "stilbite",
      "stishovite",
      "stolzite",
      "strengite",
      "sugilite",
      "sunstone",
      "susannite",
      "sylvite",
      "serandite",
      "taaffeite",
      "tactite",
      "talc",
      "tantalite",
      "tanzanite",
      "thomsonite",
      "thulite",
      "tiger's-eye",
      "tinaksite",
      "tinzenite",
      "titanite",
      "topaz",
      "tourmaline",
      "tremolite",
      "trinitite",
      "tsavorite",
      "tschermakite",
      "tugtupite",
      "turquoise",
      "tusionite",
      "tyrolite",
      "unakite",
      "uvarovite",
      "vanadinite",
      "variscite",
      "vauxite",
      "vermiculite",
      "vesuvianite",
      "villiaumite",
      "wakefieldite",
      "wavellite",
      "weloganite",
      "wolfenite",
      "xenotime",
      "yttrium aluminium garnet",
      "zektzerite",
      "zeolite",
      "zincite",
      "zinnwaldite",
      "zircon",
      "zoisite"
    ],

    "passages": [
        "corridor",
        "doorway",
        "entrance",
        "gate",
        "hatch",
        "passage",
        "passageway",
        "path",
        "pit",
        "stairway",
        "trail",
        "tunnel"
    ],

    "moods" : [
		"abandoned",
		"barren",
		"closed",
		"condemned",
		"dark",
		"dead",
		"desolate",
		"destroyed",
		"distant",
		"guarded",
		"haunted",
		"hostile",
		"melancholic",
		"nasty",
		"neglected",
		"overloaded",
		"protected",
		"sabotaged",
		"superior",
		"terrifying",
		"tormented",
		"uncanny",
		"vacant",
	]


}

grammar = tracery.Grammar(rules)
grammar.add_modifiers(base_english)


def generate_world_title():
    print grammar.flatten("#origin#")  # prints, e.g., "Hello, world!"

